// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzFDq6gU7h3vfVzXz-ceYfuEvmzGlBejM',
    appId: '1:293217955343:web:02d9d2e54452550c6e3d7a',
    messagingSenderId: '293217955343',
    projectId: 'agrotech-2c731',
    authDomain: 'agrotech-2c731.firebaseapp.com',
    storageBucket: 'agrotech-2c731.firebasestorage.app',
    measurementId: 'G-BRT7JKEQHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC4at5D5kiaFxxbuEAnenmxwJzqGGS2eg',
    appId: '1:293217955343:android:074e19a0d0a3a3286e3d7a',
    messagingSenderId: '293217955343',
    projectId: 'agrotech-2c731',
    storageBucket: 'agrotech-2c731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGJo1_759E3Vy1YwlOfvhNiG8aJKxsPsg',
    appId: '1:293217955343:ios:c02cc449157edc2e6e3d7a',
    messagingSenderId: '293217955343',
    projectId: 'agrotech-2c731',
    storageBucket: 'agrotech-2c731.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGJo1_759E3Vy1YwlOfvhNiG8aJKxsPsg',
    appId: '1:293217955343:ios:c02cc449157edc2e6e3d7a',
    messagingSenderId: '293217955343',
    projectId: 'agrotech-2c731',
    storageBucket: 'agrotech-2c731.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzFDq6gU7h3vfVzXz-ceYfuEvmzGlBejM',
    appId: '1:293217955343:web:107d1b5e346c60cc6e3d7a',
    messagingSenderId: '293217955343',
    projectId: 'agrotech-2c731',
    authDomain: 'agrotech-2c731.firebaseapp.com',
    storageBucket: 'agrotech-2c731.firebasestorage.app',
    measurementId: 'G-KSF61K1RS1',
  );
}
